- hosts: node
  become: yes


  vars:
    - homeDir: /home/ubuntu
    - appDir : app
    - repo: devops_test
    - account: ashishkamat2791
    


  tasks:
  - name: Install Packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - build-essential
      - npm
      - nodejs-legacy
      - git
      - mcrypt
      - nginx
      - curl

  - name: Install pm2
    npm: name=pm2 global=yes production=yes

  - name: Create APP Directory
    file: path={{homeDir}}/{{appDir}} state=directory

  - name: Git Clone Repo
    git: repo=https://github.com/{{account}}/{{repo}}.git dest={{homeDir}}/{{appDir}} update=yes force=yes
    register: git_finished

  - name: Running NPM install
    npm: path={{homeDir}}/{{appDir}}/backened
    register: npm_finished
    when: git_finished.changed

  - name: Stop APP
    become_user: ubuntu
    command: pm2 stop app chdir={{homeDir}}/{{appDir}}/backened
    ignore_errors: yes

  - name: Start APP
    become_user: ubuntu
    command: pm2 start index.js --name app chdir={{homeDir}}/{{appDir}}/backened
    ignore_errors: yes
    when: npm_finished.changed